apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    reindex.remote.whitelist: "10.197.129.28:31920"
