apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 7 
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
#     volumes:
#      - name: data
#        persistentVolumeClaim:
#          claimName: elastic-data      
     containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
        resources:
            limits:
              cpu: "3"
              memory: 8G
            requests:
              memory: 8G
              cpu: "3"
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: xpack.security.enabled
            value: 'false'
          - name: ingest.geoip.downloader.enabled
            value: 'false'
#          - name: ES_JAVA_OPTS
#            value: '-Xms8192m -Xmx8192m'
          - name: MAX_OPEN_FILES
            value: '5000000'
          - name: MAX_LOCKED_MEMORY
            value: unlimited
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch,es-cluster-3.elasticsearch,es-cluster-4.elasticsearch,es-cluster-5.elasticsearch,es-cluster-6.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2,es-cluster-3,es-cluster-4,es-cluster-5,es-cluster-6"
     initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elastic-data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 30Gi
